### ISSUE TITLE
Acesso

### ISSUE THREAD

**Issue by danielpaulo199** [VictorIsra/sistema-de-encartes-nuxt-fabric#2]
olá achei muito interessante o projeto, porem quando clonei o repositório para da uma olhada ele pede Usuário e senha, poderia me falar como faço?

**Comment by VictorIsra** [comment]
Olá, Daniel! Tudo bem? em pages > login.vue eu crio um user padrão, caso não exista. login: root, senha toor123456. qualquer coisa, pode checar no arquivo!
